language: php
sudo: required
php:
 - '7.0'
 - '7.1'
 - '7.2'
 - '7.3'
 - '7.4'

services:
 - mysql

before_script:
 - composer self-update
 - chmod ugo+x bin/travis.sh
 - ./bin/travis.sh $(phpenv version-name) $(pwd)

install:
 - travis_retry composer install --no-interaction --prefer-source --dev

notifications:
 on_success: never
 on_failure: always
